name: PyTest
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pip install -r requirements.txt

      - name: Run test suite
        run: |
          pytest
      - name: Create GitHub Issue on Test Failure
        if: ${{ failure() }}
        run: |
          $url = "https://api.github.com/repos/${{ github.repository }}/issues"
          $headers = @{
            "Authorization" = "Bearer $env:GITHUB_TOKEN"
            "Content-Type" = "application/json"
          }
          $body = @{
            title = "Test Failure"
            body = "Tests failed. Check the test results."
            labels = @("pytest", "test-failure")
          } | ConvertTo-Json

          Invoke-RestMethod -Uri $url -Headers $headers -Method Post -Body $body
